### ISSUE TITLE
自定义控件垂直间隙问题

### ISSUE THREAD

**Issue by zxdeer** [LineChen/AutoNewLineLayout#1]
我自定义每个控件宽度，但是设置垂直间隙无效

**Comment by LineChen** [comment]
@zhiwo 动态修改了子控件的宽度吗？可以贴一下代码吗

**Comment by zxdeer** [comment]
![image](https://cloud.githubusercontent.com/assets/4919430/24031071/66d68998-0b1b-11e7-8316-3e796cba657d.png)

**Comment by zhiwo** [comment]
![Uploading image.png…]()

我这样会有效果

**Comment by zxdeer** [comment]
![image](https://cloud.githubusercontent.com/assets/4919430/24031106/aa639d2c-0b1b-11e7-9ac7-31d681e06d65.png)
wozhey我这样会有效果

**Comment by LineChen** [comment]
@zhiwo 
![1489732064 1](https://cloud.githubusercontent.com/assets/11845769/24031560/3a19bec2-0b1e-11e7-89d7-9d5f790f0c59.jpg)
你在布局文件中设置就可以了

**Comment by zxdeer** [comment]
设置了无效啊。。。。

**Comment by LineChen** [comment]
@zhiwo ..我测试了一下这段代码，用了三个手机测试，没出现问题
![default](https://cloud.githubusercontent.com/assets/11845769/24032100/40b46874-0b21-11e7-9a04-c1488649d85a.png)

**Comment by zxdeer** [comment]
好吧，我再看看
